namespace Xbox360.Remote.Cli.Commands;

internal static class XeCliTerminalPaletteCatalog {
    private static readonly string[] s_terminalPaletteKnownPaths = [
        "connect",
        "status",
        "scan",
        "target",
        "report",
        "ping",
        "profiles",
        "title",
        "reboot",
        "shutdown",
        "launch",
        "notify",
        "screenshot",
        "install",
        "start",
        "language",
        "health",
        "log list",
        "log export",
        "diagnostics bundle",
        "support bundle",
        "homebrew list",
        "homebrew install",
        "ogxbox list",
        "ogxbox install",
        "fatman devices",
        "fatman disks",
        "fatman partitions",
        "fatman scan",
        "fatman info",
        "fatman list",
        "fatman find",
        "fatman get",
        "fatman cat",
        "fatman mkdir",
        "fatman put",
        "fatman mv",
        "fatman rm",
        "fatman format",
        "fatman check",
        "fatman repair",
        "fatman extract",
        "fatman dump",
        "xbdm info",
        "xbdm raw",
        "xbdm screenshot",
        "xbdm modules list",
        "xbdm modules info",
        "xbdm modules address",
        "xbdm modules dump",
        "xbdm modules load",
        "xbdm modules unload",
        "xbdm modules pending",
        "xbdm mem dump",
        "xbdm mem hexdump",
        "xbdm mem regions",
        "xbdm mem map",
        "xbdm mem diff",
        "xbdm mem dump-diff",
        "xbdm mem session create",
        "xbdm mem session list",
        "xbdm mem session show",
        "xbdm mem session remove",
        "xbdm mem peek",
        "xbdm mem poke",
        "xbdm mem watch",
        "xbdm mem strings",
        "xbdm mem find",
        "trainer apply",
        "trainer run",
        "xbdm xex dump",
        "xbdm xex launch",
        "xbdm xex strings",
        "xbdm xex info",
        "xbdm xex map",
        "xbdm xex decompile",
        "xbdm xex ida-decompile",
        "xex bundle",
        "xbdm fs list",
        "xbdm fs get",
        "xbdm fs put",
        "xbdm fs cat",
        "xbdm fs rm",
        "xbdm fs mkdir",
        "xbdm fs mv",
        "xbdm threads list",
        "xbdm threads context",
        "xbdm threads suspend",
        "xbdm threads resume",
        "xbdm debug watch",
        "xbdm debug stop",
        "xbdm debug go",
        "xbdm debug break add",
        "xbdm debug break remove",
        "xbdm debug break clearall",
        "xbdm debug address-check",
        "xbdm debug databreak add",
        "xbdm debug databreak remove",
        "jrpc2 cpu-key",
        "jrpc2 temps",
        "jrpc2 title-id",
        "jrpc2 dashboard",
        "jrpc2 motherboard",
        "smc version",
        "smc temps",
        "fan set",
        "fan show",
        "led set",
        "led state",
        "signin state",
        "tray open",
        "tray close",
        "popup show",
        "ftp target",
        "ftp check",
        "ftp list",
        "ftp find",
        "ftp get",
        "ftp put",
        "ftp sync",
        "ftp cat",
        "ftp hash",
        "ftp diff",
        "ftp rm",
        "ftp mkdir",
        "ftp mv",
        "target-profile add",
        "target-profile list",
        "target-profile show",
        "target-profile validate",
        "target-profile remove",
        "target-profile use",
        "target-profile current",
        "save list",
        "save extract",
        "save inject",
        "content list",
        "content delete",
        "con info",
        "con verify",
        "con rehash",
        "con resign",
        "con magic-name",
        "con fatx-path",
        "profile info",
        "profile extract",
        "profile account show",
        "profile account extract",
        "profile account set-gamertag",
        "profile gpd list",
        "profile gpd extract",
        "profile titles list",
        "profile titles add",
        "profile achievements list",
        "profile achievements unlock",
        "profile achievements lock",
        "profile settings list",
        "profile settings get",
        "profile settings set",
        "profile avatar-colors get",
        "profile avatar-colors set",
        "xdbf list",
        "xdbf get",
        "xdbf extract",
        "xdbf sync-status",
        "avatar games",
        "avatar items",
        "avatar choose",
        "avatar browse",
        "avatar install",
        "avatar cache status",
        "avatar cache refresh",
        "avatar library show",
        "avatar library set",
        "plugin list",
        "plugin enable",
        "plugin disable",
        "god info",
        "god build",
        "god watch",
        "ghidra config",
        "ghidra analyze",
        "ghidra export-symbols",
        "ghidra decompile",
        "ghidra verify",
        "xtaf-cli config",
        "xtaf-cli status",
        "xtaf-cli install",
        "xtaf-cli run",
        "ida config",
        "ida check",
        "ida install-loader",
        "ida analyze",
        "ida export-symbols",
        "ida decompile",
        "ida verify",
        "mem-bookmarks add",
        "mem-bookmarks rename",
        "mem-bookmarks export",
        "mem-bookmarks import",
        "mem-bookmarks show",
        "mem session create",
        "mem session list",
        "mem session show",
        "mem session remove",
        "bookmarks import",
        "memmarks import",
        "help",
        "--version",
        "exit"
    ];

    private static readonly string[] s_quickActionSuggestions = [
        "connect --ip ",
        "status",
        "status --quick",
        "status --json",
        "scan",
        "target",
        "report --include-modules --include-threads --out .\\console-report.md",
        "support bundle --out .\\xecli-support.zip",
        "ping",
        "profiles",
        "title",
        "reboot",
        "shutdown",
        "launch --xex ",
        "notify --message ",
        "screenshot",
        "ftp target --ip ",
        "ftp check",
        "ftp list --path ",
        "ftp get --path ",
        "ftp get --path /Hdd1/example --out .\\download --recursive --verify-hash sha256",
        "ftp put --in ",
        "ftp put --in .\\folder --path /Hdd1/example/ --recursive --dry-run --verify-hash sha256",
        "ftp sync",
        "save list",
        "save extract --title ",
        "save inject --title ",
        "content list",
        "content delete --id ",
        "fatman devices",
        "fatman disks",
        "fatman partitions --disk ",
        "fatman scan --image ",
        "fatman info --image ",
        "fatman list --image ",
        "fatman find --image ",
        "fatman get --image ",
        "fatman cat --image ",
        "fatman mkdir --image ",
        "fatman put --image ",
        "fatman mv --image ",
        "fatman rm --image ",
        "fatman format --image ",
        "fatman check --image ",
        "fatman repair --image ",
        "fatman extract --image ",
        "fatman dump --image ",
        "xbdm info",
        "xbdm raw ",
        "xbdm modules list",
        "xbdm modules info --name ",
        "xbdm modules address --name ",
        "xbdm modules dump --name ",
        "xbdm mem regions",
        "xbdm mem dump --addr ",
        "xbdm mem dump --module default.xex --rva  --size  --out dump.bin",
        "xbdm mem hexdump --addr ",
        "xbdm mem hexdump --module default.xex --rva  --size ",
        "xbdm mem strings --addr ",
        "xbdm mem find --type ",
        "trainer apply --file .\\trainer.json",
        "trainer run --file .\\trainer.json",
        "xbdm xex dump",
        "debug watch --require-event",
        "xbdm debug break add --module default.xex --rva ",
        "xbdm debug address-check --module default.xex --rva ",
        "xbdm debug address-check --module default.xex --ghidra  --ghidra-base ",
        "xbdm debug databreak add --module default.xex --ghidra  --ghidra-base ",
        "xbdm threads list",
        "jrpc2 cpu-key",
        "jrpc2 temps",
        "jrpc2 title-id",
        "jrpc2 dashboard",
        "jrpc2 motherboard",
        "smc version",
        "smc temps",
        "fan set --speed ",
        "fan show",
        "led set --preset all-green",
        "led state",
        "ghidra config",
        "ghidra analyze --in ",
        "ghidra export-symbols --in .\\game.xex --out .\\symbols.json",
        "xex bundle --file .\\game.xex --out .\\xex-bundle.zip",
        "xtaf-cli status",
        "xtaf-cli install",
        "xtaf-cli run --arg=--help",
        "ida export-symbols --in .\\game.i64 --out .\\symbols.json",
        "ida check",
        "ida analyze --in ",
        "mem-bookmarks rename --name KernelEntry --to KernelEntry2",
        "mem-bookmarks show --name KernelEntry",
        "mem-bookmarks export --out .\\memory-bookmarks.json",
        "mem-bookmarks import --file .\\symbols.json",
        "mem session create --name lab --capture map:baseline=.\\left.json --capture dump:before=.\\left.bin",
        "mem session show --name lab",
        "help",
        "--version",
        "exit"
    ];

    private static readonly string[] s_registeredCommandPaths = CompletionScriptBuilder.RegisteredCommandPaths
        .Concat(s_terminalPaletteKnownPaths)
        .Distinct(StringComparer.OrdinalIgnoreCase)
        .OrderBy(path => path, StringComparer.OrdinalIgnoreCase)
        .ToArray();
    private static readonly string[] s_registeredCommandPathsBySpecificity = s_registeredCommandPaths
        .OrderByDescending(path => path.Count(character => character == ' '))
        .ThenByDescending(path => path.Length)
        .ToArray();
    public static IReadOnlyList<string> RegisteredCommandPaths => s_registeredCommandPaths;

    public static IReadOnlyList<string> QuickActions => s_quickActionSuggestions;

    internal static IEnumerable<string> GetRegisteredSuggestions(IEnumerable<string> suggestions) {
        HashSet<string> seenSuggestions = new(StringComparer.OrdinalIgnoreCase);
        foreach (string suggestion in suggestions) {
            if (!TryGetRegisteredCommandPath(suggestion, out _)) {
                continue;
            }

            if (seenSuggestions.Add(suggestion)) {
                yield return suggestion;
            }
        }
    }

    internal static bool TryGetRegisteredCommandPath(string suggestion, out string commandPath) {
        string normalized = suggestion.Trim();
        foreach (string candidate in s_registeredCommandPathsBySpecificity) {
            if (normalized.Equals(candidate, StringComparison.OrdinalIgnoreCase) ||
                normalized.StartsWith(candidate + " ", StringComparison.OrdinalIgnoreCase)) {
                commandPath = candidate;
                return true;
            }
        }

        commandPath = string.Empty;
        return false;
    }
}
