/* AUTO GENERATED BY make. DO NOT EDIT! */

#define RELEASE "v0.993-d4f08b4"
#define BLAME "LibXenon.org"
#define DATE "2026-03-24"
#define GITREV "d4f08b4"

#define VERSION RELEASE "-git-" GITREV
#define LONGVERSION VERSION " " DATE " (" BLAME ")"
#define GCC_VERSION "9.2.0"
#define BINUTILS_VERSION "2.32"
